name: booklyapp
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: '>=3.4.4 <4.0.0'
dependencies:
    cupertino_icons: ^1.0.6
    equatable: ^2.0.5
    flutter:
        sdk: flutter
    json_annotation: any
    freezed_annotation: any
    font_awesome_flutter: ^10.7.0
    go_router: ^14.2.7
    google_fonts: ^6.2.1
    provider: ^6.0.5
    flutter_localizations:
        sdk: flutter
    shared_preferences: ^2.1.1
    flutter_secure_storage: ^8.0.0
    sqflite: ^2.2.8+2
    path: ^1.8.2
    cloud_firestore: ^4.6.0
    cloud_functions: ^4.2.0
    firebase_storage: ^11.1.2
    logger: ^1.3.0
    firebase_crashlytics: ^3.2.0
    firebase_auth: ^4.5.0
    google_sign_in: ^6.1.0
dev_dependencies:
    flutter_lints: ^3.0.0
    flutter_test:
        sdk: flutter
    json_serializable: any
    build_runner: any
    freezed: any
flutter:
    uses-material-design: true
    assets:
        - assets/images/
    fonts:
        -
            family: GT Sectra Fine
            fonts:
                -
                    asset: assets/fonts/GT Sectra Fine Regular.ttf
