name: booklyapp
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^4.6.0
  cloud_functions: ^4.2.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.5
  firebase_auth: ^4.5.0
  firebase_crashlytics: ^3.2.0
  firebase_storage: ^11.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  font_awesome_flutter: ^10.7.0
  freezed_annotation: any
  get_it: ^7.7.0
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  google_sign_in: ^6.1.0
  json_annotation: any
  logger: ^1.3.0
  path: ^1.8.2
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  sqflite: ^2.2.8+2
  url_launcher: ^6.3.0
dev_dependencies:
  build_runner: any
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: any
  json_serializable: any
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: GT Sectra Fine
      fonts:
        - asset: assets/fonts/GT Sectra Fine Regular.ttf
